apps/locaux/urls.py
from django.conf.urls import patterns, url 

import views

urlpatterns = patterns('',
#    url('^$', views.redirect_to_view, name="root"),
    url('^$', views.view, name="view"),
    url('^intervention/(?P<iid>\d+)/$', views.intervention, name="intervention"),
#    url('^validate/(.+)?$', views.validate, name="validate"),
)

urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, patterns, url
import settings
import django.contrib.auth.views
from bw_comp.protectpost import protect

from django.contrib import admin
admin.autodiscover()

if settings.CAS_ENABLED:
    login_url = url('^login', 'django_cas.views.login', name="login")
    logout_url = url('^logout', 'django_cas.views.logout', name="logout")
else:
    login_url = url('^login', protect(django.contrib.auth.views.login), {'template_name': 'login.html'}, name="login")
    logout_url = url('^logout', 'django.contrib.auth.views.logout_then_login', name ="logout")

urlpatterns = patterns('',
    # Les pages existantes
    url('^$', 'apps.accueil.views.view', name='index'),
    # Pages de login
    login_url,
    logout_url,
    (r'^admin/', include(admin.site.urls)),
    (r'^heartbeat$', 'bw_comp.heartbeat.view'),
    )

if settings.DEV:
    # Quand on utilise le serveur de DEV, on veut que Django serve les static files
    urlpatterns += patterns('', url('^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':'static/'}),
                           )

for app in settings.INTRANET_APPS:
    app = app["name"]
    urlpatterns += patterns('', ('^%s/' % app, include('apps.%s.urls' % app,
                                                       namespace = app,
                                                       app_name = app)))

# Pour une raison inconnue, ces valeurs par défaut ne sont pas définies ...
handler404='django.views.defaults.page_not_found'
handler403='django.views.defaults.permission_denied'
handler500='django.views.defaults.server_error'

apps/locaux/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

class Local(models.Model):
    u"""Un local, que ce soit Crans ou Crous"""
    is_local = True
    class Meta:
        verbose_name_plural = "locaux"
        ordering = ['batiment', 'etage']
    batiment = models.CharField(max_length=1)
    etage = models.IntegerField()
    description = models.CharField(max_length=255, blank=True, null=True)

    def __unicode__(self):
        if self.description != '':
            comment = u" (%s)" % self.description
        else:
            comment = u""
        return u"%d%s%s" % (self.etage, self.batiment, comment)

    def get_clefs(self):
        return Clef.objects.filter(local__exact=self)

class Clef(models.Model):
    u"""Une clé, un proprio, pour un local"""
    local = models.ForeignKey(Local)
    proprietaire = models.ForeignKey(User)
    description = models.CharField(max_length=255, blank=True, null=True)

    def get_next_interventions(self):
        # La relation "exact" est en fait, une inclusion, comme on peut
        # s'y attendre (un vrai "exact" serait vraiment lourd)
        return Intervention.objects.filter(clefs__exact=self)

    def __unicode__(self):
        if self.description != '':
            comment = u" (%s)" % self.description
        else:
            comment = u""
        return u"%d%s%s - %s %s" % (self.local.etage, self.local.batiment,\
                                 comment, self.proprietaire.first_name, \
                                 self.proprietaire.last_name)


class Intervention(models.Model):
    u"""Une intervention, peut-être planifiée"""
    class Meta:
        permissions = (("can_view", u"Peut voir les interventions"),
                       ("can_create", u"Peut créer son intervention"))
        ordering = ['-debut', 'intervenant']
    ETAT_CHOICES = (
        ('prevu',u'Prévu'),
        ('en_cours',u'En cours'),
        ('termine',u'Terminé'),
        ('annule',u'Annulé'),
    )

    intervenant = models.ForeignKey(User)
    titre = models.CharField(max_length=255, blank=False, null=False)
    clefs = models.ManyToManyField(Clef)
    debut = models.DateTimeField()
    fin = models.DateTimeField()
    etat = models.CharField(max_length=8, choices=ETAT_CHOICES)
    description = models.TextField()
    
    def __unicode__(self):
        base = self.titre + " par " + self.intervenant.first_name + " " + \
               self.intervenant.last_name
        return base

    @models.permalink
    def get_absolute_url(self):
        return ('intervention', (), {'iid': self.id})

apps/locaux/views.py
# -*- encoding: utf-8 -*-
# Create your views here.
import django.shortcuts
from django.http import Http404
from django.template import RequestContext

from django.contrib.auth.decorators import login_required, permission_required

from models import Clef, Local, Intervention

class Proprio:
    is_proprio = True
    def __init__(self, user, name=None):
        self.user = user
        if name == None:
            name = u"%s %s" % (user.first_name, user.last_name)
        self.name = name

    def get_clefs(self):
        return Clef.objects.filter(proprietaire__exact=self.user)

    def __unicode__(self):
        return self.name

from django.contrib.auth.decorators import login_required, permission_required

@permission_required('locaux.can_view')
def view(request):
    t = {'groupe_list': [Proprio(request.user, u"Mes clés")] +
                         list(Local.objects.all()) }
    return django.shortcuts.render_to_response("locaux/liste_clefs.html", t,\
            context_instance=RequestContext(request))

@permission_required('locaux.can_view')
def intervention(request, iid):
    try:
        [interv] = list(Intervention.objects.filter(id__exact=iid))
        return django.shortcuts.render_to_response("locaux/intervention.html",\
            {'intervention': interv},\
            context_instance=RequestContext(request))
    except ValueError:
        raise Http404

templates/locaux/base.html
{% extends "template.html" %}
{% load full_name %}
{% block title %}Accès aux locaux{% endblock %}
{% block head %}{% endblock %}
{% block h1 %}<h1>Accès aux locaux</h1>{% endblock %}

templates/locaux/intervention.html
{% extends "locaux/base.html" %}
{% load full_name %}
{% block title %}{{ block.super }} : Détail de l'intervention{% endblock %}
{% block h1 %}{{block.super}}<h2> Détail de l'intervention </h2>{% endblock %}
{% block content %}
{% autoescape on %}
<h3>{{intervention.titre}}</h3>
<p>
  <ul>
    <li>Intervenant : {{ intervention.intervenant|full_name }}</li>
    <li>Début : {{ intervention.debut }}</li>
    <li>Fin : {{ intervention.fin }}</li>
    <li>Statut : {{ intervention.get_etat_display }}</li>
  </ul>
</p>
<h4>Description</h4>
{{ intervention.description|urlize|linebreaks }} 
{% endautoescape %}
{% endblock %}

templates/locaux/liste_clefs.html
{% extends "locaux/base.html" %}
{% load full_name %}
{% block content %}
{% for groupe in groupe_list %}
  <div>
    <h3>{{groupe}}</h3>
    <table>
    {% if groupe.get_clefs|length > 0 %}
      <tr>
        {% if not groupe.is_local %}<td>Local</td>{%endif%}
        {% if not groupe.is_proprio %}<td>Propriétaire</td>{% endif %}
        <td>Notes</td>
        <td>Interventions prévues</td>
      </tr>
      {% for clef in groupe.get_clefs %}
      <tr>
        {% if not groupe.is_local %}<td>{{clef.local|escape}}</td>{% endif %}
        {% if not groupe.is_proprio %}<td>{{clef.proprietaire|full_name|escape}}
        </td>{% endif %}
        <td>{{clef.description|escape}}</td>
        <td>
        {% for inter in clef.get_next_interventions %}
            <a href="{{inter.get_absolute_url}}">{{inter.debut}}</a>
        {% endfor %}
        </td>
      </tr>
      {% endfor %}
    </table>
    {% else %}
        <p>Aucune clé</p>
    {% endif %}
  </div>
{% endfor %}
{% endblock %}